/**
 * Hey Bradley — Project ZIP Export
 * Bundles all specs + config into a downloadable ZIP file.
 * ADR-036: Pure client-side, no server needed.
 */

import JSZip from 'jszip'
import type { MasterConfig } from '@/lib/schemas'
import {
  generateNorthStar,
  generateSADD,
  generateBuildPlan,
  generateFeatures,
  generateHumanSpec,
  generateAISPSpec,
} from '@/lib/specGenerators'

/**
 * Generate all specs and bundle them into a ZIP, then trigger browser download.
 */
export async function exportProjectAsZip(config: MasterConfig): Promise<void> {
  const zip = new JSZip()

  // Generate all 6 specs
  const northStar = generateNorthStar(config)
  const sadd = generateSADD(config)
  const buildPlan = generateBuildPlan(config)
  const features = generateFeatures(config)
  const humanSpec = generateHumanSpec(config)
  const aispSpec = generateAISPSpec(config)
  const jsonConfig = JSON.stringify(config, null, 2)

  // Add specs to ZIP
  const specs = zip.folder('specs')!
  specs.file('north-star.md', northStar)
  specs.file('architecture.md', sadd)
  specs.file('build-plan.md', buildPlan)
  specs.file('features.md', features)
  specs.file('human-spec.md', humanSpec)
  specs.file('aisp.aisp', aispSpec)

  // Add config
  zip.file('config.json', jsonConfig)

  // Add README overview
  const siteName = config.site?.title || 'Untitled Project'
  const readme = [
    `# ${siteName} — Hey Bradley Export`,
    '',
    `Exported: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Contents',
    '',
    '- `specs/north-star.md` — North Star vision document',
    '- `specs/architecture.md` — Solution Architecture (SADD)',
    '- `specs/build-plan.md` — Build plan with component spec',
    '- `specs/features.md` — Feature list with acceptance criteria',
    '- `specs/human-spec.md` — Human-readable specification',
    '- `specs/aisp.aisp` — AISP Crystal Atom machine-parseable spec',
    '- `config.json` — Full JSON configuration',
    '',
    '## How to Use',
    '',
    '1. Open `specs/build-plan.md` in Claude Code or your AI tool of choice',
    '2. Paste as your prompt with "Build this in React + Tailwind"',
    '3. Your site is ready in minutes',
    '',
    '---',
    'Generated by [Hey Bradley](https://hey-bradley.com)',
  ].join('\n')
  zip.file('README.md', readme)

  // Generate ZIP blob and trigger download
  const blob = await zip.generateAsync({ type: 'blob' })
  const slug = siteName.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'project'
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${slug}-export.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
