import type { MasterConfig } from '@/lib/schemas'
import { SECTION_LABELS, SECTION_DESCRIPTIONS, getComponentText, describeComponentProps, describePaletteSlot } from './helpers'

/**
 * Human Spec Generator (P76 / OC-9 polish) — formatted markdown document with
 * proper headings, table-of-contents, atom counts, and substantive sections.
 *
 * Reads like a real spec document, not template scaffolding. All concrete
 * values are pulled from MasterConfig — no fabricated content.
 *
 * Sections:
 *   1. Overview            — auto-generated paragraph from tagline + theme + section count
 *   2. Site Architecture   — Pages + Sections (numbered, with variant + CTA)
 *   3. Theme & Typography  — primary color, fonts, radius
 *   4. Color Palette       — 6-slot palette table
 *   5. Content Strategy    — tone-derived paragraph
 *   6. Acceptance Criteria — concrete, checkable acceptance gates
 *   7. Implementation Notes — concrete build steps from section variants
 *   8. Section Details     — full untruncated detail (preserved from prior generator)
 */
export function generateHumanSpec(config: MasterConfig): string {
  const { site, theme, sections } = config
  const enabled = sections.filter((s) => s.enabled)
  const disabled = sections.filter((s) => !s.enabled)

  const purpose = (site as Record<string, unknown>).purpose as string || 'marketing'
  const audience = (site as Record<string, unknown>).audience as string || 'consumer'
  const tone = (site as Record<string, unknown>).tone as string || 'casual'
  const tagline = (site as Record<string, unknown>).tagline as string || ''
  const brandName = (site as Record<string, unknown>).brandName as string || site.title || ''
  const voiceAttributes = (site as Record<string, unknown>).voiceAttributes as string[] || []

  const date = new Date().toISOString().split('T')[0]
  const title = site.title || 'Untitled Website'

  // -------------------------------------------------------------------------
  // Header — document title + generation metadata
  // -------------------------------------------------------------------------
  let spec = `# ${title} — Specification\n\n`
  spec += `> Generated by Hey Bradley · ${date}\n`
  spec += `> Atoms: 5 · Spec format: HUMAN · Version: ${site.version || '1.0.0-RC1'}\n`
  spec += `> Sections: ${enabled.length} active${disabled.length > 0 ? ` · ${disabled.length} disabled` : ''}\n\n`

  // -------------------------------------------------------------------------
  // Table of Contents
  // -------------------------------------------------------------------------
  spec += `## Contents\n\n`
  spec += `1. Overview\n`
  spec += `2. Site Architecture\n`
  spec += `3. Theme & Typography\n`
  spec += `4. Color Palette\n`
  spec += `5. Content Strategy\n`
  spec += `6. Acceptance Criteria\n`
  spec += `7. Implementation Notes\n`
  spec += `8. Section Details\n\n`
  spec += `---\n\n`

  // -------------------------------------------------------------------------
  // 1. Overview — substantive paragraph derived from real config fields
  // -------------------------------------------------------------------------
  spec += `## 1. Overview\n\n`
  spec += `**${brandName || title}** is a ${tone} ${purpose} site targeting a ${audience} audience. `
  if (tagline) spec += `The tagline reads: "${tagline}". `
  if (site.description) spec += `${site.description} `
  spec += `The site is built on the "${theme.preset || 'custom'}" design system in ${theme.mode} mode `
  spec += `and uses ${enabled.length} content section${enabled.length === 1 ? '' : 's'} to guide visitors from awareness to action.\n\n`
  if (voiceAttributes.length > 0) {
    spec += `Voice attributes: ${voiceAttributes.map((v) => `*${v}*`).join(', ')}.\n\n`
  }

  // -------------------------------------------------------------------------
  // 2. Site Architecture
  // -------------------------------------------------------------------------
  spec += `## 2. Site Architecture\n\n`
  spec += `### Pages\n`
  spec += `- Home (current)\n\n`
  spec += `### Sections\n`
  enabled.forEach((s, i) => {
    const label = SECTION_LABELS[s.type] || s.type
    const variant = s.variant ? ` (${s.variant})` : ''
    const heading = (s.content as Record<string, unknown>)?.heading as string | undefined
    spec += `${i + 1}. **${label}**${variant}`
    if (heading) spec += ` — "${heading}"`
    spec += `\n`
  })
  if (disabled.length > 0) {
    spec += `\n_Disabled:_ ${disabled.map((s) => SECTION_LABELS[s.type] || s.type).join(', ')}\n`
  }
  spec += `\n`

  // -------------------------------------------------------------------------
  // 3. Theme & Typography
  // -------------------------------------------------------------------------
  spec += `## 3. Theme & Typography\n\n`
  spec += `| Property | Value |\n|----------|-------|\n`
  spec += `| Theme preset | ${theme.preset || 'custom'} |\n`
  spec += `| Mode | ${theme.mode} |\n`
  spec += `| Primary color | \`${theme.palette?.accentPrimary || '—'}\` |\n`
  spec += `| Heading font | ${theme.typography?.headingFamily || theme.typography?.fontFamily || 'Inter'} |\n`
  spec += `| Body font | ${theme.typography?.fontFamily || 'Inter'} |\n`
  spec += `| Heading weight | ${theme.typography?.headingWeight || 700} |\n`
  spec += `| Base size | ${theme.typography?.baseSize || '16px'} |\n`
  spec += `| Line height | ${theme.typography?.lineHeight || 1.7} |\n`
  spec += `| Border radius | ${theme.borderRadius || '12px'} |\n`
  spec += `| Section padding | ${theme.spacing?.sectionPadding || '64px'} |\n`
  spec += `| Container max-width | ${theme.spacing?.containerMaxWidth || '1280px'} |\n`
  spec += `| Component gap | ${theme.spacing?.componentGap || '24px'} |\n`
  spec += `\n`

  // -------------------------------------------------------------------------
  // 4. Color Palette
  // -------------------------------------------------------------------------
  if (theme.palette) {
    spec += `## 4. Color Palette\n\n`
    spec += `| Slot | Hex | Role |\n|------|-----|------|\n`
    for (const [key, value] of Object.entries(theme.palette)) {
      spec += `| ${describePaletteSlot(key)} | \`${value}\` | ${key} |\n`
    }
    spec += `\n`
  }

  // -------------------------------------------------------------------------
  // 5. Content Strategy — derived paragraph
  // -------------------------------------------------------------------------
  spec += `## 5. Content Strategy\n\n`
  spec += `Copy across all sections holds a **${tone}** tone for a **${audience}** audience. `
  if (voiceAttributes.length > 0) {
    spec += `Voice attributes (${voiceAttributes.join(', ')}) shape every headline, button label, and microcopy decision. `
  }
  spec += `Sections were selected to support a ${purpose} narrative: `
  spec += enabled.map((s) => SECTION_LABELS[s.type] || s.type).join(' → ')
  spec += `.\n\n`

  // -------------------------------------------------------------------------
  // 6. Acceptance Criteria — concrete checkable gates
  // -------------------------------------------------------------------------
  spec += `## 6. Acceptance Criteria\n\n`
  spec += `- [ ] Hero renders within 100ms on first paint\n`
  spec += `- [ ] All ${enabled.length} sections produce semantically valid HTML5\n`
  spec += `- [ ] Mobile-responsive at 375 / 768 / 1024 breakpoints\n`
  spec += `- [ ] WCAG 2.1 AA contrast ratios met on every text/background pair\n`
  spec += `- [ ] Theme tokens (palette + typography + spacing) inlined in static HTML export\n`
  const ctaSection = enabled.find((s) => s.type === 'action' || s.type === 'hero')
  if (ctaSection) {
    spec += `- [ ] Primary CTA on **${SECTION_LABELS[ctaSection.type] || ctaSection.type}** is reachable in ≤2 scroll-screens on mobile\n`
  }
  spec += `\n`

  // -------------------------------------------------------------------------
  // 7. Implementation Notes — concrete build steps from section variants
  // -------------------------------------------------------------------------
  spec += `## 7. Implementation Notes\n\n`
  enabled.forEach((s, i) => {
    const label = SECTION_LABELS[s.type] || s.type
    const variant = s.variant || 'default'
    spec += `${i + 1}. Build **${label}** with the \`${variant}\` variant`
    if (s.style?.imageEffect && s.style.imageEffect !== 'none') {
      spec += `; apply \`${s.style.imageEffect}\` image effect`
    }
    const compCount = (s.components ?? []).filter((c) => c.enabled).length
    if (compCount > 0) spec += ` · ${compCount} component${compCount === 1 ? '' : 's'}`
    spec += `.\n`
  })
  spec += `\n`

  // -------------------------------------------------------------------------
  // 8. Section Details — full untruncated technical surface
  // -------------------------------------------------------------------------
  spec += `## 8. Section Details\n\n`
  enabled.forEach((s) => {
    const label = SECTION_LABELS[s.type] || s.type
    const description = SECTION_DESCRIPTIONS[s.type] || ''

    spec += `### ${label}\n\n`
    if (description) spec += `${description}\n\n`

    // Properties table
    spec += `| Property | Value |\n|----------|-------|\n`
    spec += `| Type | \`${s.type}\` |\n`
    if (s.variant) spec += `| Variant | \`${s.variant}\` |\n`
    if (s.style?.background) spec += `| Background | \`${s.style.background}\` |\n`
    if (s.style?.color) spec += `| Text color | \`${s.style.color}\` |\n`
    if (s.style?.fontFamily) spec += `| Font | ${s.style.fontFamily} |\n`
    if (s.style?.imageEffect && s.style.imageEffect !== 'none') {
      const effectNames: Record<string, string> = {
        'ken-burns': 'Ken Burns zoom', 'slow-pan': 'slow pan', 'zoom-hover': 'zoom on hover',
        'click-enlarge': 'click-to-enlarge lightbox', 'gradient-overlay': 'gradient overlay',
        'parallax': 'parallax scrolling', 'glass-blur': 'frosted glass blur',
        'grayscale-hover': 'grayscale to color on hover', 'vignette': 'vignette',
        'holographic': 'holographic glow', 'tilt-3d': '3D tilt on hover',
        'sepia-to-color': 'sepia to color on hover', 'reveal-slide': 'reveal slide on hover',
        'fade-in-scroll': 'fade in on scroll',
      }
      spec += `| Image Effect | ${effectNames[s.style.imageEffect] || s.style.imageEffect} |\n`
    }

    const heading = (s.content as Record<string, unknown>)?.heading as string | undefined
    const subheading = (s.content as Record<string, unknown>)?.subheading as string | undefined
    if (heading) spec += `| Heading | "${heading}" |\n`
    if (subheading) spec += `| Subheading | "${subheading}" |\n`

    if (s.layout) {
      const layoutParts: string[] = []
      if (s.layout.display) layoutParts.push(`display: ${s.layout.display}`)
      if (s.layout.columns) layoutParts.push(`cols: ${s.layout.columns}`)
      if (s.layout.gap) layoutParts.push(`gap: ${s.layout.gap}`)
      if ((s.layout as Record<string, unknown>)?.padding) layoutParts.push(`padding: ${(s.layout as Record<string, unknown>)?.padding}`)
      if (layoutParts.length > 0) spec += `| Layout | ${layoutParts.join(', ')} |\n`
    }
    spec += `\n`

    // Components — ALL of them, NO slice, FULL text
    const activeComps = (s.components ?? []).filter((c) => c.enabled)
    if (activeComps.length > 0) {
      spec += `**Components (${activeComps.length}):**\n\n`
      activeComps.forEach((c) => {
        const text = getComponentText(c)
        spec += `- **\`${c.id}\`** (${c.type})`
        if (text) spec += `: "${text}"`
        spec += `\n`
        const props = describeComponentProps(c)
        props.forEach((p) => {
          spec += `  - ${p}\n`
        })
      })
      spec += `\n`
    }
  })

  return spec.trimEnd() + '\n'
}
