import type { MasterConfig } from '@/lib/schemas'
import { getSpecTemplate } from '@/data/spec-templates'
import { SECTION_DESCRIPTIONS, SECTION_LABELS, PRESET_MOODS } from './helpers'

/**
 * North Star Generator (P76 / OC-9 polish) — vision document that reads like
 * a real founder/PM-authored brief. A reader understands the entire project
 * (what / why / success / out-of-scope / roadmap) in 5 minutes.
 *
 * Polish notes:
 *   - "What we're building" — concrete 2-3 sentences from title + sections + theme
 *   - "Why it matters" — pulled from tagline / description / voiceAttributes
 *   - "What success looks like" — concrete bullets with measurable thresholds
 *   - "Out of scope" — disabled section types + BYOK-only honesty
 *   - "Roadmap" — concrete 3-step ship plan from real section list
 *
 * Section order and labels are still driven by the north-star template JSON;
 * each renderer below pulls real content from MasterConfig — no fabrication.
 */
export function generateNorthStar(config: MasterConfig): string {
  const template = getSpecTemplate('north-star')
  const { site, theme, sections } = config
  const enabled = sections.filter((s) => s.enabled)
  const title = site.title || 'Untitled Website'
  const desc = site.description || ''
  const mood = PRESET_MOODS[theme.preset] || 'Custom visual theme'
  const heroSection = enabled.find((s) => s.type === 'hero')
  const heroHeadline = heroSection ? getHeroHeadline(heroSection) : ''
  const ctaSection = enabled.find((s) => s.type === 'action')
  const ctaText = ctaSection ? getCtaText(ctaSection) : ''
  const hasTestimonials = enabled.some((s) => s.type === 'quotes')
  const hasPricing = enabled.some((s) => s.type === 'pricing')
  const hasNumbers = enabled.some((s) => s.type === 'numbers')
  const disabled = sections.filter((s) => !s.enabled)

  const purpose = (site as Record<string, unknown>).purpose as string || 'marketing'
  const audience = (site as Record<string, unknown>).audience as string || 'consumer'
  const tone = (site as Record<string, unknown>).tone as string || 'casual'
  const brandName = (site as Record<string, unknown>).brandName as string || title
  const tagline = (site as Record<string, unknown>).tagline as string || ''
  const voiceAttributes = (site as Record<string, unknown>).voiceAttributes as string[] || []

  // Shared context passed to each section renderer
  const ctx: RenderContext = {
    site, theme, sections, enabled, disabled, title, desc, mood,
    heroHeadline, ctaText, hasTestimonials, hasPricing, hasNumbers,
    purpose, audience, tone, brandName, tagline, voiceAttributes,
  }

  const date = new Date().toISOString().split('T')[0]

  // --- Header (vision document framing) ---
  let spec = `# ${title} — North Star\n\n`
  spec += `> Generated by Hey Bradley · ${date}\n`
  spec += `> Atoms: 5 · Spec format: NORTH_STAR · Version: ${site.version || '1.0.0-RC1'}\n\n`
  spec += `This North Star captures the product vision, market fit, and success criteria for **${title}**. `
  spec += `It is the strategic guide for every design and development decision — read it before changing anything material.\n\n`

  // --- Executive Summary (P76 polish) ---
  spec += `## What we're building\n\n`
  spec += `**${brandName}** is a ${tone} ${purpose} site for a ${audience} audience, built on the "${theme.preset || 'custom'}" design system in ${theme.mode} mode. `
  if (tagline) spec += `In one line: *"${tagline}"*. `
  if (desc) spec += `${desc} `
  spec += `The site uses ${enabled.length} content section${enabled.length === 1 ? '' : 's'} (${enabled.map((s) => SECTION_LABELS[s.type] || s.type).join(', ')}) to take a visitor from awareness to action.\n\n`

  spec += `## Why it matters\n\n`
  if (tagline || desc || voiceAttributes.length > 0) {
    if (tagline) spec += `The promise: *${tagline}*. `
    if (voiceAttributes.length > 0) spec += `Voice: ${voiceAttributes.join(', ')}. `
    if (desc) spec += `${desc}\n\n`
    else spec += `\n\n`
  } else {
    spec += `_(No tagline or description set yet — fill these in via the chat to make this paragraph concrete.)_\n\n`
  }

  spec += `## What success looks like\n\n`
  spec += `- Visitors understand the offer in under 5 seconds (hero headline + primary CTA visible without scroll)\n`
  spec += `- Mobile-first; first paint in under 2 seconds on a 4G connection\n`
  spec += `- Clean conversion funnel: ${enabled.map((s) => SECTION_LABELS[s.type] || s.type).join(' → ')}\n`
  spec += `- WCAG 2.1 AA contrast on every text/background pair\n`
  if (heroHeadline) spec += `- Hero headline tests above 70% comprehension in 5-second tests: "${heroHeadline}"\n`
  if (ctaText) spec += `- Primary CTA "${ctaText}" achieves a measurable click-through baseline\n`
  spec += `\n`

  spec += `## Out of scope\n\n`
  if (disabled.length > 0) {
    spec += `- Section types not used in this build: ${disabled.map((s) => SECTION_LABELS[s.type] || s.type).join(', ')}\n`
  }
  spec += `- Hosted infrastructure (Hey Bradley is BYOK / static-export only)\n`
  spec += `- Server-side personalization (current export is a single static HTML page)\n`
  spec += `- Multi-page navigation beyond the home page (handled in a follow-up)\n\n`

  spec += `## Roadmap\n\n`
  spec += `1. Ship the core sections: ${enabled.map((s) => SECTION_LABELS[s.type] || s.type).join(', ')}\n`
  spec += `2. Iterate copy and design via the chat — every change re-emits this North Star + AISP atom bundle\n`
  spec += `3. Export the static HTML (\`{slug}-export.zip\`) and host on the user's own infrastructure\n\n`

  spec += `---\n\n`

  // --- Template-driven sections (preserved from prior generator) ---
  const templateSections = template.sections ?? []
  templateSections.forEach((section, idx) => {
    const renderer = sectionRenderers[section.id]
    if (renderer) {
      spec += renderer(idx + 1, section.label, ctx)
    }
  })

  return spec
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface RenderContext {
  site: MasterConfig['site']
  theme: MasterConfig['theme']
  sections: MasterConfig['sections']
  enabled: MasterConfig['sections']
  disabled: MasterConfig['sections']
  title: string
  desc: string
  mood: string
  heroHeadline: string
  ctaText: string
  hasTestimonials: boolean
  hasPricing: boolean
  hasNumbers: boolean
  purpose: string
  audience: string
  tone: string
  brandName: string
  tagline: string
  voiceAttributes: string[]
}

type SectionRenderer = (num: number, label: string, ctx: RenderContext) => string

// ---------------------------------------------------------------------------
// Section renderers — keyed by template section id
// ---------------------------------------------------------------------------

const sectionRenderers: Record<string, SectionRenderer> = {
  overview(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    s += `| Property | Value |\n|----------|-------|\n`
    s += `| **Title** | ${ctx.title} |\n`
    if (ctx.brandName && ctx.brandName !== ctx.title) s += `| **Brand** | ${ctx.brandName} |\n`
    if (ctx.tagline) s += `| **Tagline** | ${ctx.tagline} |\n`
    s += `| **Purpose** | ${ctx.purpose} |\n`
    s += `| **Audience** | ${ctx.audience} |\n`
    s += `| **Tone** | ${ctx.tone} |\n`
    if (ctx.voiceAttributes.length > 0) s += `| **Voice** | ${ctx.voiceAttributes.join(', ')} |\n`
    if (ctx.site.author) s += `| **Author** | ${ctx.site.author} |\n`
    if (ctx.site.email) s += `| **Email** | ${ctx.site.email} |\n`
    if (ctx.site.domain) s += `| **Domain** | ${ctx.site.domain} |\n`
    s += `| **Theme** | ${ctx.theme.preset || 'custom'} (${ctx.theme.mode}) |\n`
    s += `| **Border Radius** | ${ctx.theme.borderRadius || '12px'} |\n`
    s += `| **Spacing** | padding ${ctx.theme.spacing?.sectionPadding || '64px'}, max-width ${ctx.theme.spacing?.containerMaxWidth || '1280px'}, gap ${ctx.theme.spacing?.componentGap || '24px'} |\n`
    s += `\n`
    return s
  },

  vision(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    s += `**${ctx.brandName}** is a ${ctx.theme.mode === 'dark' ? 'dark-themed' : 'light-themed'} ${ctx.purpose} site `
    s += `built on the "${ctx.theme.preset || 'custom'}" design system. `
    if (ctx.tagline) s += `Tagline: *"${ctx.tagline}"*. `
    if (ctx.desc) s += `${ctx.desc} `
    s += `\n\nThe site uses ${ctx.enabled.length} content section${ctx.enabled.length === 1 ? '' : 's'} to guide visitors from awareness to action. `
    s += `The visual mood is: *${ctx.mood}*.\n\n`
    if (ctx.disabled.length > 0) {
      s += `**Disabled sections:** ${ctx.disabled.map(sec => SECTION_LABELS[sec.type] || sec.type).join(', ')}\n\n`
    }
    return s
  },

  product_market_fit(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    s += `| Element | Value |\n|---------|-------|\n`
    if (ctx.heroHeadline) s += `| **Value Proposition** | "${ctx.heroHeadline}" |\n`
    s += `| **Target Audience** | ${ctx.audience} — ${inferAudience(ctx.theme.preset, ctx.enabled)} |\n`
    if (ctx.ctaText) s += `| **Primary Action** | "${ctx.ctaText}" |\n`
    s += `| **Trust Signals** | ${inferTrustSignals(ctx.enabled)} |\n`
    s += `| **Sections** | ${ctx.enabled.length} active (${ctx.enabled.map(sec => SECTION_LABELS[sec.type] || sec.type).join(', ')}) |\n\n`
    return s
  },

  site_structure(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    ctx.enabled.forEach((sec, i) => {
      const sLabel = SECTION_LABELS[sec.type] || sec.type
      const description = SECTION_DESCRIPTIONS[sec.type] || ''
      const heading = (sec.content as Record<string, unknown>)?.heading as string
      s += `${i + 1}. **${sLabel}**`
      if (sec.variant) s += ` (${sec.variant})`
      if (heading) s += ` — "${heading}"`
      s += `\n   ${description}\n\n`
    })
    return s
  },

  user_personas(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    s += `### First-Time Visitor\n`
    s += `- **Goal:** Understand what ${ctx.brandName} offers in under 10 seconds\n`
    s += `- **Entry point:** Hero section${ctx.heroHeadline ? ` with headline "${ctx.heroHeadline}"` : ''}\n`
    s += `- **Journey:** Hero → ${ctx.hasNumbers ? 'Stats (reviews key metrics) → ' : ''}${ctx.hasPricing ? 'Pricing (compares pricing tiers) → ' : ''}${ctx.hasTestimonials ? 'Testimonials (reads social proof) → ' : ''}CTA\n`
    s += `- **Success metric:** Clicks primary CTA${ctx.ctaText ? ` ("${ctx.ctaText}")` : ''}\n\n`
    s += `### Returning Visitor\n`
    s += `- **Goal:** Find specific information or take action\n`
    s += `- **Entry point:** Navigation bar or direct link\n`
    s += `- **Journey:** Nav → ${ctx.hasPricing ? 'Pricing (compares plans)' : 'Specific section'} → Action\n`
    s += `- **Success metric:** Completes conversion or finds needed info\n\n`
    return s
  },

  success_criteria(num, label, ctx) {
    let s = `## ${num}. ${label}\n\n`
    s += `1. **First impression (< 3s):** Visitor understands the value proposition from the hero headline\n`
    s += `2. **Visual quality:** Site looks like a funded product, not a template\n`
    s += `3. **Mobile responsive:** All ${ctx.enabled.length} sections render correctly at 375px\n`
    s += `4. **Accessibility:** WCAG 2.1 AA contrast ratios on all text\n`
    s += `5. **Performance:** Initial paint < 2 seconds on 4G connection\n`
    const effectSections = ctx.enabled.filter(sec => sec.style?.imageEffect && sec.style.imageEffect !== 'none')
    if (effectSections.length > 0) {
      const effects = [...new Set(effectSections.map(sec => sec.style!.imageEffect!))]
      s += `6. **Image effects:** ${effects.join(', ')} effects render smoothly at 60fps\n`
    }
    return s
  },
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function getHeroHeadline(section: { components?: Array<{ id: string; props?: Record<string, unknown> }> }): string {
  const headline = section.components?.find((c) => c.id === 'headline')
  return (headline?.props?.text as string) || ''
}

function getCtaText(section: { components?: Array<{ id: string; type: string; props?: Record<string, unknown> }> }): string {
  const btn = section.components?.find((c) => c.type === 'button' || c.id === 'button')
  return (btn?.props?.text as string) || ''
}

function inferAudience(preset: string, sections: Array<{ type: string }>): string {
  const map: Record<string, string> = {
    saas: 'a SaaS product or technical service',
    agency: 'creative or professional agency services',
    portfolio: 'a creative professional\'s portfolio',
    blog: 'written content and thought leadership',
    startup: 'an innovative product or technology',
    personal: 'a personal brand or individual service',
    professional: 'professional or consulting services',
    wellness: 'a wellness, food, or lifestyle brand',
    creative: 'a creative or artistic offering',
    minimalist: 'a clean, focused product or service',
  }
  return map[preset] || `the products and services offered (${sections.length} sections)`
}

function inferTrustSignals(sections: Array<{ type: string }>): string {
  const signals: string[] = []
  if (sections.some(s => s.type === 'quotes')) signals.push('Customer testimonials')
  if (sections.some(s => s.type === 'logos')) signals.push('Partner/client logos')
  if (sections.some(s => s.type === 'numbers')) signals.push('Key metrics/statistics')
  if (sections.some(s => s.type === 'team')) signals.push('Team member profiles')
  return signals.length > 0 ? signals.join(', ') : 'None configured'
}
