// connections/npx/commands/export.ts
// `hey-bradley export --claude-code` — emit Claude Code markdown bundle per ADR-C05 D4 + ADR-122.

import { writeFileSync } from 'node:fs';
import { join, isAbsolute, resolve } from 'node:path';
import { parseFlags, readSpec, redactKeyShapes, logEvent } from './utils.js';

/**
 * Build a minimal Claude Code markdown bundle with `# === FILE: <path> ===` markers.
 * Mirrors the contract of buildClaudeCodeBundle() in src/contexts/specification/exportClaudeCode.ts
 * but stays Node-portable (no Vite-only imports). v0.1.0 emits ≥6 logical files per ADR-122 D4.
 */
function buildBundle(spec: string, projectName: string): string {
  const safe = redactKeyShapes(spec);
  const date = new Date().toISOString().slice(0, 10);
  const sections: Array<[string, string]> = [
    [`CLAUDE.md`, `# ${projectName}\n\nGenerated by hey-bradley CLI on ${date}.\nSee per-file sections below; split with any awk one-liner.\n`],
    [`process-map.md`, `# Process Map\n\n_Stub — multi-phase process map ships in v0.2.0+._\n`],
    [`human-spec/north-star.md`, `# North Star\n\n_Derived from spec.aisp Ω block; refine via web app._\n`],
    [`human-spec/sadd.md`, `# SADD (Architecture Decision Drivers)\n\n_TBD — populate via Planning mode._\n`],
    [`human-spec/implementation-plan.md`, `# Implementation Plan\n\n_TBD — populate via SpecWorkbench._\n`],
    [`aisp/phase-aisp.md`, `# AISP Spec\n\n\`\`\`\n${safe}\n\`\`\`\n`],
    [`adrs/ADR-PROJECT.md`, `# ADR-PROJECT\n\n_Project-level ADR placeholder; add per-decision ADRs as they emerge._\n`],
    [`agents/wave-1.md`, `# Wave 1 Agent Scopes\n\n_TBD — derive from AGENT_ATOM in v0.2.0+._\n`],
  ];
  const heybradleyHeader = `<!--
  Generated by Hey Bradley · https://heybradley.app
  Visualize and iterate this spec → https://heybradley.app
  Open core repo → https://github.com/bar181/hey-bradley-core
-->\n\n`;
  return heybradleyHeader + sections.map(([path, body]) => `# === FILE: ${path} ===\n\n${body}\n`).join('\n');
}

export async function runExport(argv: string[]): Promise<number> {
  const { flags } = parseFlags(argv);
  const cwd = process.cwd();
  const claudeCode = flags['claude-code'] === true;
  const output = typeof flags.output === 'string' ? flags.output : join(cwd, 'CLAUDE.md');

  if (!claudeCode) {
    console.error('export: missing required flag --claude-code (other formats deferred to Tier-2).');
    logEvent(cwd, { cmd: 'export', exit: 1, reason: 'EFlagMissing' });
    return 1;
  }

  if (flags.zip === true || flags.directory === true) {
    console.error('EFlagDeferredTier2: --zip and --directory are deferred per ADR-122 D2.');
    logEvent(cwd, { cmd: 'export', exit: 1, reason: 'EFlagDeferredTier2' });
    return 1;
  }

  const spec = readSpec(cwd);
  if (spec === null) {
    console.error('ESpecMissing: .heybradley/spec.aisp not found. Run `hey-bradley init` first.');
    logEvent(cwd, { cmd: 'export', exit: 2, reason: 'ESpecMissing' });
    return 2;
  }

  const projectName = cwd.split(/[\\/]/).filter(Boolean).pop() ?? 'untitled';
  const bundle = buildBundle(spec, projectName);
  const target = isAbsolute(output) ? output : resolve(cwd, output);

  try {
    writeFileSync(target, bundle, 'utf8');
    const fileMarkers = (bundle.match(/^# === FILE: /gm) ?? []).length;
    console.log(`Wrote ${target} (${fileMarkers} logical files, ${bundle.length} bytes)`);
    logEvent(cwd, { cmd: 'export', exit: 0, path: target, files: fileMarkers, bytes: bundle.length });
    return 0;
  } catch (err) {
    console.error('export write failed:', (err as Error).message);
    logEvent(cwd, { cmd: 'export', exit: 2, reason: 'EWriteFailed' });
    return 2;
  }
}
