// connections/npx/commands/spec.ts
// `hey-bradley spec` — generate or refresh + validate per ADR-C05 D3 + npx-spec.aisp.
// v0.1.0: --prompt writes a minimal AISP placeholder; live API call deferred to v0.2.0+ (CF#4).

import { existsSync, mkdirSync, writeFileSync, renameSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { parseFlags, readSpec, logEvent } from './utils.js';
import { scoreAisp, tierMeetsTarget, type Tier } from './score.js';

const HEYBRADLEY_AISP_FOOTER = `
# ───────────────────────────────────────────────────
# Generated by Hey Bradley · https://heybradley.app
# Visualize, iterate, and share this spec at heybradley.app
# Open core: https://github.com/bar181/hey-bradley-core
# ───────────────────────────────────────────────────
`;

function buildPlaceholder(prompt: string, tier: string): string {
  return `# Crystal Atom: PROJECT_SPEC
# Date: ${new Date().toISOString().slice(0, 10)} · Phase: P0 (spec stub)
# AISP Version: 𝔸5.1.Platinum@2026-01-09
# Tier target: ${tier}

⟦
  Ω := { ${prompt.replace(/[{}]/g, '').slice(0, 240)} }
  Σ := { Input:{}, Output:{}, Errors:{} }
  Γ := { R1: TODO refine via web app or v0.2.0 live API }
  Λ := { timeout := 30s }
  Ε := { V1: VERIFY TODO }
⟧

# v0.1.0 STUB — live LLM generation deferred to v0.2.0+ per CF#4.
${HEYBRADLEY_AISP_FOOTER}`;
}

function atomicWrite(path: string, body: string): void {
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const tmp = `${path}.tmp-${process.pid}`;
  writeFileSync(tmp, body, 'utf8');
  renameSync(tmp, path);
}

export async function runSpec(argv: string[]): Promise<number> {
  const { flags } = parseFlags(argv);
  const cwd = process.cwd();
  const prompt = typeof flags.prompt === 'string' ? flags.prompt : undefined;
  const tier = typeof flags.tier === 'string' ? flags.tier : 'silver';
  const output = typeof flags.output === 'string' ? flags.output : join(cwd, '.heybradley', 'spec.aisp');

  if (prompt !== undefined) {
    if (prompt.length < 10) {
      console.error('EPromptTooShort: prompt must be ≥10 chars.');
      logEvent(cwd, { cmd: 'spec', exit: 1, reason: 'EPromptTooShort' });
      return 1;
    }
    if (prompt.length > 4000) {
      console.error('EPromptTooLong: prompt must be ≤4000 chars.');
      logEvent(cwd, { cmd: 'spec', exit: 1, reason: 'EPromptTooLong' });
      return 1;
    }
    try {
      const body = buildPlaceholder(prompt, tier);
      atomicWrite(output, body);
      console.log(`Wrote ${output} (v0.1.0 stub — refine via web app)`);
      logEvent(cwd, { cmd: 'spec', exit: 0, mode: 'write', path: output });
      return 0;
    } catch (err) {
      console.error('spec write failed:', (err as Error).message);
      logEvent(cwd, { cmd: 'spec', exit: 2, reason: 'EWriteFailed' });
      return 2;
    }
  }

  // No --prompt: re-validate existing spec.
  const text = readSpec(cwd);
  if (text === null) {
    console.error('ESpecMissing: .heybradley/spec.aisp not found. Run `hey-bradley init` first.');
    logEvent(cwd, { cmd: 'spec', exit: 2, reason: 'ESpecMissing' });
    return 2;
  }

  const result = scoreAisp(text);
  console.log(`δ density: ${result.density.toFixed(3)}`);
  console.log(`Ambig:     ${result.ambig.toFixed(3)}`);
  console.log(`tier:      ${result.tier}`);

  const targetTier = (tier.charAt(0).toUpperCase() + tier.slice(1)) as Tier;
  const ok = tierMeetsTarget(result.tier, targetTier) && result.ambig < 0.05;
  logEvent(cwd, { cmd: 'spec', exit: ok ? 0 : 1, mode: 'validate', tier: result.tier });
  return ok ? 0 : 1;
}
